### ISSUE TITLE
Install for MacOS failed

### ISSUE THREAD

**Issue by mielune** [Lucterios2/core#11]
Hi,

I try to install on OS X El Capitan and it failed
I used the command line 
curl -s https://raw.githubusercontent.com/Lucterios2/setup/master/install.sh | bash -s --
And it failed trying to create the virtualenv due to the missing installation of the virtualenv in /Library/Frameworks/Python.framework/Versions/3.5/bin
I added this folder in the path and retry an installation.

The script ended successfully by no script to start Diacama2.

I looked in the install.sh script and I saw 3 lines with double @@ for values : 
EXTRA_URL="@@URL@@"
PACKAGES="@@PACKAGE@@"
APP_NAME="@@NAME@@"
Perhaps something missing here.

This are the last lines from the install:

Installed /private/var/lucterios2/.eggs/altgraph-0.12-py3.5.egg
running py2app
creating /private/var/lucterios2/build
creating /private/var/lucterios2/build/bdist.macosx-10.6-intel
creating /private/var/lucterios2/build/bdist.macosx-10.6-intel/python3.5-standalone
creating /private/var/lucterios2/build/bdist.macosx-10.6-intel/python3.5-standalone/app
creating /private/var/lucterios2/build/bdist.macosx-10.6-intel/python3.5-standalone/app/collect
creating /private/var/lucterios2/build/bdist.macosx-10.6-intel/python3.5-standalone/app/temp
creating /private/var/lucterios2/dist
creating build/bdist.macosx-10.6-intel/python3.5-standalone/app/lib-dynload
creating build/bdist.macosx-10.6-intel/python3.5-standalone/app/Frameworks
**\* creating application bundle: @@NAME@@ ***
Done!
============ END =============

I hope this will help.

Laurent

**Comment by GayLaurent** [comment]
Hi,

sorry, our wiki and our setup git repo were not upgraded.
Try again:

```
curl -s https://raw.githubusercontent.com/Lucterios2/setup/master/install_mac.sh --output install_mac.sh
bash install_mac.sh -p "lucterios_standard" -n "Lucterios"
```
