### ISSUE TITLE
Error while trying to start lucterios ( Apache 2.4 / Debian 7 )

### ISSUE THREAD

**Issue by FroggDev** [Lucterios2/core#12]
Hi,

I installed all as the tutorial said:

_1st way_
- extract & copy file from http://www.sd-libre.fr/download/Lucterios_setup.tar.gz
- launch installer : bash install.sh
- cd /var/lucterios2/virtual_for_lucterios/bin

_2nd way_
- curl -s https://raw.githubusercontent.com/Lucterios2/setup/master/install.sh | bash -s --
- pip install -t web/lucterios -U lucterios-standard
- cd lucterios/install/

then i am launching the command (with both installation) : 

`python lucterios_admin.py add -n test-i /var/www/`

with error message:

> Traceback (most recent call last):
>   File "lucterios_admin.py", line 34, in <module>
>     from django.utils import six
> ImportError: No module named django.utils

so i tried to edit line 34:

```
#from django.utils import six
import six
```

but now i get this error:

> Traceback (most recent call last):
>  File "lucterios_admin.py", line 1006, in <module>
>    main()
>  File "lucterios_admin.py", line 966, in main
>    getattr(luct, args[0])()
>  File "lucterios_admin.py", line 651, in add
>    self.refresh()
>  File "lucterios_admin.py", line 711, in refresh
>    self.read()
>  File "lucterios_admin.py", line 580, in read
>    clear_modules()
>  File "lucterios_admin.py", line 75, in clear_modules
>    import django.conf
> ImportError: No module named django.conf

Any idea ?

Thanks

PS:
if i copy django folder

`cp /var/lucterios2/virtual_for_lucterios/lib/python3.4/site-packages/django /var/lucterios2/virtual_for_lucterios/bin -r`

the error change to 

> ImportError: No module named lucterios.framework.settings

then if i copy lucterios folder

`cp /var/lucterios2/virtual_for_lucterios/lib/python3.4/site-packages/lucterios /var/lucterios2/virtual_for_lucterios/bin -r`

the error change to 

> ImportError: No module named lxml

 etc ...

so i added a symbolic link to site-packages/\* in /var/lucterios2/virtual_for_lucterios/bin

but now i am stuck at 

> ImportError: cannot import name etree

i tried to add a virtual link to /usr/lib/python3.4/ or /usr/lib/python2.7/, but the error still occur

**Comment by GayLaurent** [comment]
Hi,

sorry, our wiki and our setup git repo were not upgraded.
Try again:

```
 curl -s https://raw.githubusercontent.com/Lucterios2/setup/master/install.sh --output install.sh
 bash install.sh -p "lucterios_standard" -n "Lucterios"
```
